# Sử dụng image PostgreSQL chính thức
FROM postgres:15-alpine

# Thiết lập biến môi trường
ENV POSTGRES_USER=traceability
ENV POSTGRES_PASSWORD=traceability
ENV POSTGRES_DB=traceability
# Mở cổng mặc định
EXPOSE 5432