import { founderImage } from "@/public/images";
import { FounderData } from "@/types";

export const founderData: FounderData[] = [
  {
    id: 1,
    firstName: "Tien",
    lastName: "Nguyen Anh",
    role: "Computer Science Experts",
    avatar: founderImage.tien.src,
    telegram: "https://t.me/tiennguyenanh",
    linkedin: "https://www.linkedin.com/in/tienna/",
    description: "Founder of the VILAI stake pool, former Experts at HPE; Blockchain Support Engineer",
  },
  {
    id: 2,
    firstName: "Hieu",
    lastName: "Nguyen Van",
    role: "MSc. Electronics and Telecommunication",
    avatar: founderImage.hieu.src,
    telegram: "https://t.me/nvhieu1978",
    linkedin: "https://www.linkedin.com/in/nguyen-van-hieu-b4410121b/",
    description: "Founder of HADA stake pool, member of Plutus Pioneer Program, Researcher at VAST.",
  },
  {
    id: 3,
    firstName: "Thanh",
    lastName: "Dinh Khuat",
    role: "Project Manager",
    avatar: founderImage.thanh.src,
    telegram: "https://t.me/robertkhuat",
    linkedin: "",
    description: "More than 1 years of leading and managing the operations of the projects, organizations, and club.",
  },
  {
    id: 4,
    firstName: "Khanh",
    lastName: "Nguyen Duy",
    role: "Full-stack Developer/Blockchain Developer",
    avatar: founderImage.khanh.src,
    telegram: "https://t.me/khanhnguyen1711",
    linkedin: "",
    description: "More than 2 years of building and operating on the Cardano platform.",
  },
  {
    id: 4,
    firstName: "Dung",
    lastName: "Phung Tien",
    role: "Full-stack Developer/Blockchain Developer",
    avatar: founderImage.dung.src,
    telegram: "https://t.me/tidvn",
    linkedin: "https://www.linkedin.com/in/tid-vn/",
    description: "More than 2 years of building and operating on the Cardano platform.",
  },
  {
    id: 4,
    firstName: "Son",
    lastName: "Nguyen Hong",
    role: "Full-stack Developer/Blockchain Developer",
    avatar: founderImage.son.src,
    telegram: "https://t.me/sonson211992",
    linkedin: "",
    description: "More than 2 years of building and operating on the Cardano platform.",
  },
];
