services:
  ipfs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ipfs-node
    ports:
      - "4001:4001"  # Swarm port
      - "5001:5001"  # API port
      - "8080:8080"  # Gateway port
    volumes:
      - ./data:/app  # Mount directory for file uploads
    environment:
      - IPFS_SWARM_KEY=/key/swarm/psk/1.0.0/
    restart: unless-stopped